import 'dotenv/config';
import lazySizes from 'lazysizes';
import 'tui-pagination/dist/tui-pagination.min.css';
import 'modern-normalize/modern-normalize.css';
import './sass/main.scss';
import './js/mainPage';
import './js/pageSwitch';
import './js/searchQuery';
import './js/watched';
import './js/theme';
